### ISSUE TITLE
Copy paste from clipboard only works under firefox

### ISSUE THREAD

**Issue by bflorat** [JohnMcLear/ep_copy_paste_images#17]
- etherpad 1.6.3
- ep_copy_paste_images 0.0.14

Copy past from clipboad : 
- works as expected under Firefox 17, 57
- doesn't work under chrome 65 (same under Opera but I didn't test) , nothing happens on pasting (CTRL-V)

Workaround : 
- Under Chrome at least, dragging and dropping an image from windows explorer works

Thanks for this great plugin, KUTGW !

**Comment by Oremountainflorian** [comment]
Same for me, works with firefox, doesn't work with Chrome.

**Comment by JohnMcLear** [comment]
@Oremountainflorian please provide details, https://mclear.co.uk/2015/01/15/how-to-write-a-bug-report/

**Comment by Oremountainflorian** [comment]
@JohnMcLear I'll try!

**Details** 

OS: Win 8.1
Browser: Firefox 75.0
Testpad: https://board.net/ (I suppose they have ep_copy_paste_images as well as ep_upload_images installed)

**Drag and Drop (using mouse)**

- Drag and Drop onto a blank line `Works`
- Drag and drop onto content with a line `Works when cursor is on the left of the text (then the text goes below the image, no new line created, still possible to edit text, but the cursor moves gradually to the left and it's not possible to go to the left of the text as it jumps up in an instant), doesn't work when cursor is on the the right or in beetween`
- another image in the line is removed `yes`
- New image is visible `no, both images will be removed`
- Image size is maintained `no statement possible`

**Copy to clipboard/ Paste (using control c / v AND right click copy/paste) **

- Paste onto a blank line `works`
- Paste onto a line populated with content `Works when cursor is on the left of the text (then it goes below the image, no new line created, still possible to edit text, but the cursor moves gradually to the left), doesn't work when cursor is on the the right or in beetween`
- Original copy of image is kept `yes`
- New image is visible `no`
- Image size is maintained `yes`
- No text is lost `correct`
- `when I'm in the line on the left with the cursor where already an image is and press Strg+C, nothing happens (image isn't copied to clipboard)`

**Cut to clipboard/ Paste (using control x / v AND right click copy/paste AND mobile copy/paste)**

- Paste onto a blank line `doesn't work`
- Paste onto a line populated with content (IE Type Hello world first) `doesn't work`
- Original copy of image is removed `no statement possible`
- New image is visible `no statement possible`
- Image size is maintained `no statement possible`
- No text is lost `no statement possible`
- `when I'm in the line on the left with the cursor where already an image is and press Strg+X, nothing happens (image isn't copied to clipboard)`

**Image appearance**

- Image is never distorted `correct`
- Image has correct color balance `correct`

**Alignment**

- Image can be aligned using ep_align  `no statement possible`

**Resize**

- Can resize the image small/medium/large `yes, using tab (resize smaller) or shift+tab (resize larger until original size is reached) when the cursor is left of the image`

**Browser Resize**

- Can still nagivate the page `yes`
- Images can be moved / selected / resized 
  - moved `yes, clicking the image and dragging it creates an copy, then we have it twice`
  - select `Image can never be selected by tipping it, but it can be selected by dragging the cursor over several lines. But then ctrl+c/ctrl+x works to move it for example to libre office (so it's in the clipboard), but when it's copied to another place in the pad it disappears)
  - resize `works with tab/shift+tab like described above`

**Keyboard**

- Caret can be moved between images `yes, but when we have 2 images and the caret is in beetween these two, delete doesn't delete the respective line but rather the image below`
- Backspace deletes an image when caret is placed after the image `not possible, because caret/cursor always jumps to the left`
- Delete removes an image when caret is placed before the image `yes`
- Backspace deletes an image when caret is placed before the image `yes`

**Further observations**
- when I delete an image, it can't be restored with ctrl+z
- being in line below and Backspace doesn't delete the image but rather jumps to the left of the image
- when image is in the last line, it isn't possible to create an new line below. Enter moves the image below to the new line. Moving the cursor to right of the image isn't possbile as it moves directly back left

@JohnMcLear If this report is useful to you, I can do it for Chrome as well as for ep_image_upload (this seems to be less stable than ep_copy_paste_images! Best wishes!

**Comment by JohnMcLear** [comment]
Yes it's super useful, same for Chrome would be great and the other plugins!

**Comment by Oremountainflorian** [comment]
Ok, for Chrome Version 81.0.4044.113 (official build) (64-Bit) with the settings above it's quite easy. Neither drag and drop (using mouse), nor copy to clipboard and paste (using control c / v and right click copy/paste) nor Cut to clipboard/ Paste (using control x / v AND right click copy/paste) works. 

Interesting: Once the image is inside the pad, Chrome behaves similarly to Firefox, so I only make a note of the differences: 

- after I delete the image, restoring **works** with ctrl+z
- selecting (by dragging the cursor from above or below over several lines) and pasting the image at an different line in the pad works
- copying the image by dragging to a different spot (to get two equal images in the pad) doesn't work as it does under firefox

@JohnMcLear I'll repeat the test for ep_image_upload, shall I post it here or better directly on its repo? Best regards, Flo

**Comment by JohnMcLear** [comment]
Directly on image upload repo please.

**Comment by Oremountainflorian** [comment]
@JohnMcLear 

https://github.com/citizenos/ep_image_upload/issues/11

**Comment by JohnMcLear** [comment]
This is working fine for me btw, I can copy/paste images in Chrome...  ???

Maybe I fixed something that fixed it? :)
