### ISSUE TITLE
Issues and Feature request

### ISSUE THREAD

**Issue by revast** [JohnMcLear/ep_copy_paste_images#19]
- Loss of image quality - I noticed a huge loss in image quality, in both print and pad... I googled a bit and it should be possible to store base64 images without quality loss

- Deleting images not always possible, either it gets duplicated or simply "stays" - selecting the line above, the image and line below seems to fix it most of the time

- Jump in pad on resize - Fixed if you select a line near the image

I can confirm these issues.

**- Feature Request** : Saving in File System Structure. While base64 is great for few users, the more users the etherpad install has, the bigger the database gets (up to the point where you will have to pull the plug).

**Comment by JohnMcLear** [comment]
Image qual: https://github.com/JohnMcLear/ep_copy_paste_images/blob/54a1d058ae126ffbc3d1bca9ee1dddafd8131984/static/js/index.js#L220 -- I don't think we ever reduce the quality of base64 so I'm not sure why it would be reducing quality.  Sounds like browser heuristics?

Deleting images: This is probably due to the way Etherpad is handling the character we are assigning the image attribute to.  I think resolving would be more work and require some core dev.

Jump in pad on resize: Ack RE selecting line.  

RE Feature request:  Saving on file system is planned in V2 but it's not a small task, mostly because as soon as we start writing to the FS we have to think about security a lot more.

Just FWIW I wont be getting to this in 2020, the soonest will be 2021 but I'd say there is a 5% chance I will get to it in my lifetime so if someone else wants to take the reigns I would be very happy to support / promote where possible :)

**Comment by revast** [comment]
Ok, thanks for clarification.

So using this plugin on big installments (think 500+ new pads a day) is not possible for now. Maybe state this explictely on the plugin site, people (e.g from board.net) got in serious trouble using it. 

Well, then it would be at least a good idea to have a means to embed an external image; I could not (yet) determine a way to do that, is there one?

**Comment by JohnMcLear** [comment]
Yeah this plugin is defo not production ready!

We don't allow external img URIs for 2 reasons.  1. image might not be being served by same protocol (IE https) and 2. privacy.

Ignore #3 which is I'm too lazy to write it.   Seriously though afaik there is an external image plugin afaik, but IMHO it's better to bring the image into the pad as content as to avoid broken links, privacy, security and general usability issues.

**Comment by JohnMcLear** [comment]
Closing as duplicate.
